# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length
MD013: false

# TODO(#17): Fix no-missing-space-atx
MD018: false

# TODO(#17): Fix single-title/single-h1
# # MD025/single-title/single-h1 - Multiple top-level headings
# MD025:
#   # Disable checking of YAML frontmatter.
#   front_matter_title: ""
MD025: false

# TODO(#17): Fix no-trailing-punctuation
MD026: false

# MD028/no-blanks-blockquote - Blank line inside blockquote
MD028: false

# TODO(#17): Fix MD029/ol-prefix
# # MD029/ol-prefix - Ordered list item prefix
# MD029:
#   # List style
#   style: "ordered"
MD029: false

# TODO(#17): Fix list-marker-space
# MD030/list-marker-space - Spaces after list markers
# MD030:
#   # Spaces for single-line unordered list items
#   ul_single: 1
#   # Spaces for single-line ordered list items
#   ol_single: 1
#   # Spaces for multi-line unordered list items
#   ul_multi: 1
#   # Spaces for multi-line ordered list items
#   ol_multi: 1
MD030: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD034/no-bare-urls - Bare URL used
MD034: false

# TODO(#17): Fix no-emphasis-as-heading/no-emphasis-as-header
MD036: false

# TODO(#17): Fix MD037/no-space-in-emphasis
MD037: false

# TODO(#17): MD038/no-space-in-code
MD038: false

# TODO(#17): MD039/no-space-in-links
MD039: false

# TODO(#17): Fix fenced-code-language
MD040: false

# TODO(#17): Fix no-alt-text
MD045: false

# TODO(#17): Fix code-block-style
# # MD046/code-block-style - Code block style
# MD046:
#   style: "fenced"
MD046: false

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# Disable checks that currently have bugs:
# TODO(github.com/DavidAnson/markdownlint/issues/538): Re-enable when fixed.
MD051: false
# TODO(github.com/DavidAnson/markdownlint/issues/537): Re-enable when fixed.
MD053: false
