# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TODO: Atom feeds for each language.
# TODO: Set html lang for different languages.

title: Ian Lewis
email: ianmlewis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ian Lewis is a web developer living in Tokyo Japan. His current interests are
  in Go, Python, Kubernetes, and security.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ianlewis.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: IanMLewis
github_username: ianlewis

# Build settings
theme: plainwhite
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Theme
plainwhite:
  name: Ian Lewis
  tagline: Engineer in Tokyo
  # TODO: Update to use better portfolio image.
  portfolio_image: assets/portfolio.jpg

  social_links:
    twitter: IanMLewis
    github: ianlewis

  navigation:
    - title: English Blog
      url: /en
    - title: 日本語ブログ
      url: /jp
    # TODO: Add projects page.
    - title: About Me
      url: /

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: date
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
