# Jekyll site settings

# TODO(#2): Atom feeds for each language.

title: Ian Lewis
email: ianmlewis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ian Lewis is a web developer living in Tokyo Japan. His current interests are
  in Go, Python, Kubernetes, and security.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ianlewis.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: IanMLewis
github_username: ianlewis

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Theme
plainwhite:
  name: Ian Lewis
  tagline: Engineer in Tokyo
  # TODO(#3): Update to use better portfolio image.
  portfolio_image: assets/portfolio.jpg
  sitemap: true
  search: false
  dark_mode: false
  html_lang: "en"
  condensed_mobile:
    - page
    - post

  social_links:
    twitter: IanMLewis
    github: ianlewis
    mastodon: https://hachyderm.io/@ianlewis
    email: ianmlewis@gmail.com

  navigation:
    - title: English Blog
      url: /en
    - title: 日本語ブログ
      url: /jp
    # TODO(#4): Add projects page.
    - title: About Me
      url: /

  analytics_id: "G-1C2E36DTVT"

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: date
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - Makefile
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gemfiles/
  - node_modules/
  - tools/
