# Jekyll site settings

title: Ian Lewis
email: ianmlewis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ian Lewis is an engineer based in Tokyo, Japan. His current interests are
  in Container Native Security, Supply Chain Security, Containers, and Kubernetes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ianlewis.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Theme
plainwhite:
  name: Ian Lewis
  tagline: Engineer in Tokyo
  portfolio_image: assets/images/profile.png
  sitemap: true
  search: false
  dark_mode: false
  html_lang: "en"
  condensed_mobile:
    - page
    - post
    - post_list

  social_links:
    bluesky: ianlewis.org
    github: ianlewis
    mastodon: https://hachyderm.io/@ianlewis
    email: ianmlewis@gmail.com

  navigation:
    - title: English Blog
      url: /en
    - title: 日本語ブログ
      url: /jp
    - title: About Me
      url: /
    - title: Projects
      url: /projects

  analytics_id: "G-1C2E36DTVT"

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: date
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - Makefile
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gemfiles/
  - node_modules/
  - tools/
