# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: tests

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read # Needed to check out the repo.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16

      - name: install shellcheck
        env:
          SHELLCHECK_VERSION: "0.8.0"
          SHELLCHECK_CHECKSUM: "ab6ee1b178f014d1b86d1e24da20d1139656c8b0ed34d2867fbb834dad02bf0a"
        run: |
          set -euo pipefail

          # Install shellcheck
          curl -sSLo shellcheck.tar.gz "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"
          echo "shellcheck checksum is $(sha256sum shellcheck.tar.gz | awk '{ print $1 }')"
          echo "expected checksum is $SHELLCHECK_CHECKSUM"
          echo "$SHELLCHECK_CHECKSUM  shellcheck.tar.gz" | sha256sum --strict --check --status || exit 1

          tar xf shellcheck.tar.gz
          mv "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" /usr/local/bin

      - name: install actionlint
        env:
          ACTIONLINT_VERSION: "1.6.24"
          ACTIONLINT_CHECKSUM: "3c5818744143a5d6754edd3dcc4c2b32c9dfcdd3bb30e0e108fb5e5c505262d4"
        run: |
          set -euo pipefail

          # Install actionlint
          curl -sSLo actionlint.tar.gz "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          echo "actionlint checksum is $(sha256sum actionlint.tar.gz | awk '{ print $1 }')"
          echo "expected checksum is $ACTIONLINT_CHECKSUM"
          echo "$ACTIONLINT_CHECKSUM  actionlint.tar.gz" | sha256sum --strict --check --status || exit 1

          tar xf actionlint.tar.gz
          mv ./actionlint /usr/local/bin

      - run: make format-check
      - run: make lint
